### PR TITLE
Add Stylis

### PR DESCRIPTION
**Pull request by thysultan**
Machine specs

```
1.3 GHz Intel Core i5
4 GB 1600 MHz DDR3
```

Parsers

```
Rework x 12.80 ops/sec ±4.42% (36 runs sampled)
PostCSS x 21.11 ops/sec ±8.46% (57 runs sampled)
PostCSS Full x 8.15 ops/sec ±7.79% (45 runs sampled)
CSSOM x 19.20 ops/sec ±6.53% (36 runs sampled)
Mensch x 17.85 ops/sec ±13.39% (37 runs sampled)
Gonzales x 5.21 ops/sec ±7.75% (18 runs sampled)
Gonzales PE x 3.99 ops/sec ±10.37% (15 runs sampled)
CSSTree x 39.73 ops/sec ±9.18% (56 runs sampled)
ParserLib x 1.79 ops/sec ±8.58% (9 runs sampled)
Stylecow x 3.97 ops/sec ±9.48% (15 runs sampled)
Stylis x 54.28 ops/sec ±4.45% (58 runs sampled)

Fastest test is Stylis at 1.37x faster than CSSTree
```

---

Preprocessors

```
libsass x 6.83 ops/sec ±2.29% (22 runs sampled)
Rework x 10.65 ops/sec ±3.86% (55 runs sampled)
PostCSS x 16.23 ops/sec ±11.21% (47 runs sampled)
Stylecow x 2.15 ops/sec ±6.36% (15 runs sampled)
Stylus x 3.67 ops/sec ±28.12% (25 runs sampled)
Less x 4.75 ops/sec ±9.14% (29 runs sampled)
Ruby Sass x 0.31 ops/sec ±8.12% (6 runs sampled)
Stylis x 26.26 ops/sec ±5.95% (49 runs sampled)

Fastest test is Stylis at 1.62x faster than PostCSS
```

---

Prefixers

```
Autoprefixer x 13.32 ops/sec ±6.51% (67 runs sampled)
Stylecow x 2.28 ops/sec ±5.97% (16 runs sampled)
nib x 1.79 ops/sec ±25.32% (15 runs sampled)
Compass x 0.15 ops/sec ±9.34% (5 runs sampled)
Stylis x 45.52 ops/sec ±14.61% (77 runs sampled)

Fastest test is Stylis at 3.4x faster than Autoprefixer
```

### CODE REVIEW

**Comment by ai** [comment]
Thanks. Sorry, I am on Cuba without Internet. I will look after June 9.

**Comment by ai** [comment]
Really great result!

But I can’t put it to Preprocessors section, because it doesn’t support mixins and variables.

Where I can read about Stylis AST (can we compare it with other CSS parsers)? I read [plugins docs](https://github.com/thysultan/stylis.js#plugins), bur I did’t get how deep Stylis parse CSS. Can you show me plugin calls arguments for `@media {h1{color:red;}}` input?

**Comment by thysultan** [comment]
Thanks.

>But I can’t put it to Preprocessors section, because it doesn’t support mixins and variables.

Variables and mixins are pluggable with [plugins](https://github.com/thysultan/stylis.js/tree/master/plugins) but this PR doesn't use any, should i update this PR to remove it from that section? 

>Where I can read about Stylis AST?

Stylis doesn't generate an AST, everything is done in one pass that you can modify with plugins - [API on plugins](https://github.com/thysultan/stylis.js#plugins)

**Comment by ai** [comment]
> Variables and mixins are pluggable with plugins but this PR doesn't use any

Or you can add mixins and vars plugin to PR :)

> Stylis doesn't generate an AST, everything is done in one pass that you can modify with plugins - API on plugins

Can you show me plugin calls arguments for `@media {h1{color:red;}}` input? (To understand how deep you parse CSS)

**Comment by thysultan** [comment]
>Or you can add mixins and vars plugin to PR :)

Sure.

>Can you show me plugin calls arguments for @media {h1{color:red;}} input? (To understand how deep you parse CSS)

Will use `@media {h1,h2{color:red;width:0;}}` to better differentiate between a property and a selector block.

```
context: 1 // property
parents: ['@media']
selectors: ['h1', 'h2']
content: 'color:red;'
```
---
```
context: 1 // property
parents: ['@media']
selectors: ['h1', 'h2']
content: 'width:0;'
```

```
context: 2 // selector block
parents: ['@media']
selectors: ['h1', 'h2']
content: 'color:red;width:0;'
```
---
```
context: 3 // at-rule block
parents: ['']
selectors: ['@media']
content: 'h1{color:red;}'
```
---
```
context: -2 // post-processed
parents: ['']
selectors: ['']
content: '@media {h1{color:red;}}'
```

I've left out line, column and length arguments.

**Comment by ai** [comment]
Hm. With this call it will be really hard to use Stylis as parser ;). Maybe we will keep Prefixers and Processors sections? What do you think?

**Comment by thysultan** [comment]
>With this call it will be really hard to use Stylis as parser

Maybe, can't say, i can try to make a plugin that produces an AST. What kind of AST would postcss produce for the same input?

**Comment by ai** [comment]
Here is PostCSS AST (I made example more complicated):
https://astexplorer.net/#/gist/ad636cc1bcea5cb197b370b6c1ffabc6/623f56ebd3edd6d3c271262a963b17290f8a5d02

But if you want to take CSS parser market, I can recommend to parse even deeper (like csstree).

**Comment by thysultan** [comment]
From working a bit on [a linter](https://github.com/thysultan/stylis.js/tree/master/plugins/stilynt) plugin i think it might be able to produce an AST like this from just those plugin arguments, i'll play around with this and see what kind of effort that would take, thanks.

**Comment by ai** [comment]
:+1: Ping me when you will update PR :)

**Comment by thysultan** [comment]
Hi @ai, i finally got around to adding the mixin, custom-properties(variables) and calc plugins for the preprocessor test.

Regarding producing consumable AST, i managed to put together two plugins that demonstrate this.

- [AST](https://github.com/thysultan/stylis.js/tree/master/plugins/ast)
- [Byte Code](https://github.com/thysultan/stylis.js/tree/master/plugins/bytecode)

- [AST sample](https://rawgit.com/thysultan/stylis.js/master/plugins/ast/tests/index.html)

Thanks.

**Comment by ai** [comment]
Wow! Great.

I will add it today, when I will finish with Autoprefixer Rails.

**Comment by ai** [comment]
@thysultan where did you use mixin in:

```js
styi += ':root { --size: 100px; }';
for ( i = 0; i < 100; i++ ) {
    styi += 'body h1 a { color: black; }';
    styi += 'h2 { width: var(--size); }';
    styi += 'h1 { width: calc(2 * var(--size)); }';
    styi += '.search { fill: black; width: 16px; height: 16px; }';
}
```

**Comment by thysultan** [comment]
I think forgot to add that to the css, so it should be like scss mixins, so.

```scss
styi += '@mixin icon { width: 16px; height: 16px; }';
// ...
styi += '.search { fill: black; @include icon; }';
```

**Comment by ai** [comment]
I updated results. Congrats with great performance :)

**Comment by thysultan** [comment]
Thanks.

**Pull request merged**
