### PR TITLE
Update node-sass@v3.4.0

### PR DESCRIPTION
**Pull request by xzyfer**
```
libsass:   74 ms   (1.1 times faster)
PostCSS:   80 ms
Rework:    90 ms   (1.1 times slower)
Less:      210 ms  (2.6 times slower)
Stylecow:  212 ms  (2.6 times slower)
Stylus:    245 ms  (3.0 times slower)
```

### CODE REVIEW

**Comment by ai** [comment]
Nice work!

Also PostCSS [5.0 perfomance regression](https://github.com/postcss/postcss/issues/510) was in good time for you :D.

**Comment by ai** [comment]
I update PostCSS docs https://github.com/postcss/postcss/commit/9019a5802d03e11c53484b142052c1efa34e180a

**Comment by ai** [comment]
@xzyfer by some reason I have little bit different result:

```
PostCSS:   60 ms
libsass:   74 ms   (1.2 times slower)
Rework:    74 ms   (1.2 times slower)
Less:      161 ms  (2.7 times slower)
Stylus:    174 ms  (2.9 times slower)
Stylecow:  262 ms  (4.4 times slower)
Ruby Sass: 1033 ms (17.3 times slower)
```

Can you help me to find the source of difference? I also update other libraries and uses node 4.2. Can you run it again please on latest node? Also I restart a system before benchmark and do not run any background apps (like Chrome or Atom editor).

But also my laptop has very slow CPU (Yoga 3 is about new thin Macbook in CPU), but normal RAM and SSD. Maybe it is a source?

**Comment by xzyfer** [comment]
@ai it looks like the difference is so small that the benchmark is inconsistent. I get results ranging from 1.1 faster to 1.1 slower for LibSass. I'm on a 2012 MacBook Pro Retina. 

My previous tests were on iojs 2.5.0 where LibSass consistently out performed PostCSS. On Node 4 the results are less consistent.

**Pull request merged**
