### PR TITLE
Log Stylus and Less errors once instead of throw

### PR DESCRIPTION
**Pull request by CyberAP**
https://github.com/postcss/benchmark/issues/10

### CODE REVIEW

**Comment by ai** [comment]
Why we can't fix this error and trying to hide them?

I afraid that errors will make a benchmark results irrelevant.

**Comment by CyberAP** [comment]
> Why we can't fix this error and trying to hide them?

Because it's out of scope of this repo? I am afraid there's no way to fix these errors inside this repo.


> I afraid that errors will make a benchmark results irrelevant.

It seems that other parsers are purging errors as well. For example libsass has an error argument, which is ignored in the benchmark.

https://github.com/postcss/benchmark/blob/038abb02d44753e5550bb29a6ae7282ce4f77976/preprocessors.js#L139

Maybe [gulp-bench-summary](https://github.com/ai/gulp-bench-summary/blob/master/index.js) has to be altered to give summary based only on passed tests? Or give two summaries: one for all the tests that processor was able to pass, and one with reduced results for each processor limited by every test that has failed.

**Comment by ai** [comment]
Why you can't fix Less sources? We already have regexp to make input sources compatible with every preprocessor. We just need to improve it (maybe because Bootstrap added something new).

> For example libsass has an error argument

As I know, libsass will throw error.

At least, few version back I checked Sass output manually and it works correctly.

**Comment by CyberAP** [comment]
I'll post another pull request with a proper fix when available.

**Pull request closed without merging**
